name: "test-gh-expressions"

on:
  push:

permissions: {}

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  test-gh-expressions:
    strategy:
      matrix:
        include:
          - use_shared_libs: true
            upload_binaries: true

    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - run: "echo use_shared_libs=${{toJSON(matrix.use_shared_libs)}}"
      - run: "echo upload_binaries=${{toJSON(matrix.upload_binaries)}}"

      - run: "echo $PATH"

      - run: >-
          echo "/usr/bin/abc" >> "$GITHUB_PATH"

      - run: "echo $PATH"